MODULE_CUR_PATH = $(CURDIR)
MODULE_SUB_INC = include

MODULE_SUB_DIR =  wifi
MODULE_SUB_DIR += gsensor
MODULE_SUB_DIR += gps

LINK_SHARE=y
#外部的一些头文件

MODULE_NAME = Hardware
MODULE_CUR_PATH = $(CURDIR)
include $(ROOT_PATH)/Rules/platform.mk
#模块库mk  调试执行程序mk
include $(ROOT_PATH)/Rules/module.mk
