MODULE_CUR_PATH = $(CURDIR)
MODULE_SUB_DIR = src
MODULE_SUB_INC = inc
LINK_SHARE=y
# logger
MODULE_SUB_DIR += logger
MODULE_SUB_INC += logger

MODULE_NAME = Utils

include $(MODULE_CUR_PATH)/Thirdparty/utils.mk
include $(ROOT_PATH)/Rules/platform.mk
#模块库mk  调试执行程序mk
include $(ROOT_PATH)/Rules/module.mk